Repository woorifisa-service-dev-4th/frontend-1st-finance-for-goldenage, pull requests merged in 2025-01, with the labels that each got.

#7 금융 상품 조회 페이지 개발
  product_view.html
  src/image/passbook.png
Labels: enhancement

#11 5 feat 메인페이지 2
  index.html
  product_view.html
  src/img/AS.png
  src/output.css
  tailwind.config.js
Labels: enhancement

#16 [Etc] 하이퍼링크 수정
  index.html
  product_view.html
Labels: bug

#20 [Etc] dev 브랜치를 main으로 병합
  index.html
  product_view.html
Labels: bug

#25 [Doc] Edit readme
  README.md
  docs/ColorCombination.png
  docs/GitFlow.png
  docs/Preview.gif
  docs/Preview.mp4
Labels: documentation

#28 🐛 네비게이션 바 일정 크기 이상에서도 깨지는 문제 해결결
  .vscode/settings.json
  index.html
  product_view.html
  src/output.css
  tailwind.config.js
Labels: bug

#33 Mango
  .gitignore
  .prettierignore
  .prettierrc
  eslint.config.mjs
  index.html
  index_refactor.html
  package-lock.json
  package.json
  product_view.html
  product_view_refactor.html
  src/input.css
  src/output.css
  tailwind.config.js
Labels: good first issue

#42 [Feat] Backend단 추가
  db/deposits.js
  db/events.js
  db/foreign-exchange.js
  db/funds.js
  db/loans.js
  db/news.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#51 45 feat api 연동
  db/deposits.js
  db/deposits.json
  db/events.js
  db/events.json
  db/foreign-exchange.js
  db/foreign-exchange.json
  db/funds.js
  db/funds.json
  db/loans.js
  db/loans.json
  db/news.js
  db/news.json
  public/deposits.html
  public/foreign-exchange.html
  public/funds.html
  public/index.html
  public/loans.html
  public/product_view.html
  public/src/js/card-button.js
  public/src/js/index.js
  public/src/js/pagination.js
  public/src/js/product-item.js
  public/src/js/woori-box.js
  public/src/js/woori-navbar.js
  server.js
  test.html
Labels: enhancement, Refactor

#52 [Feat] CICD file added for pipeline automatically works
  .github/workflows/cicd.yml
  .github/workflows/lint.yml
  Dockerfile
Labels: cicd
